version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - haedal-mysql
      - haedal-redis
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
      SPRING_JWT_SECRET_KEY: ${SPRING_JWT_SECRET_KEY}
      AWS_IAM_ACCESS_KEY: ${AWS_IAM_ACCESS_KEY}
      AWS_IAM_SECRET_KEY: ${AWS_IAM_SECRET_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      TZ: "Asia/Seoul"
  haedal-mysql:
    image: mysql:8.0.36
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
  haedal-redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass ${SPRING_DATA_REDIS_PASSWORD} --port 6379
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"
volumes:
  db-data: